name: CI
env:
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
jobs:
  ci:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:13.2
        env:
          POSTGRES_PASSWORD: password
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18.12.0
      - run: echo "//npm.pkg.github.com/:_authToken=${{ secrets.GITHUB_TOKEN }}" >> .npmrc
      - run: npm install -g pnpm
      - run: pnpm install
      - run: rm -rf .npmrc
      - run: npx prisma migrate dev --schema node_modules/@reynandaptr/aha-types/prisma/schema.prisma --name init
        env:
          DATABASE_URL: postgresql://postgres:password@localhost:5432/aha?schema=public
      - run: pnpm test
        env:
          DATABASE_URL: postgresql://postgres:password@localhost:5432/aha?schema=public
          ENVIRONMENT: test
          APP_URL: http://localhost:3000
          DOCS_URL: https://localhost:3001
          COOKIE_DOMAIN: localhost
          JWT_PRIVATE_KEY: "-----BEGIN PRIVATE KEY-----\nMIIEvwIBADANBgkqhkiG9w0BAQEFAASCBKkwggSlAgEAAoIBAQC4mTGTUodeUaak\nCnwlaMSk3zPDifnlUyf/T40ruVSIkG2tmJMBs1ZX6YrWy+SlNzM7nsTyqdQAt9By\nbTdhpqgxCFfAXI76Kn7duSaQcVoCyldA9lHwZjlcq8ru/4sh5ePdYWxXQJ62Ukem\nqkz178tdI1D9Zr7XEB4jW4If3Lnb/oaSfaG6B0uMAWpoUsnbh2yVdKx3RMkDEWGg\nc+BTTOYoXRc8GdLM6hlCAM8IhtQ+ZhzGjZOeOqGMWHFVw67sfDQunBY6K8+Nmtap\nKQcE6EG128W6ZSgiA8dhvPToXUZNnBZsjLBehUcdjopYovtAaBg3C7LnFlmRgY08\nqTuy7BGbAgMBAAECggEAHMaEm9p5j5Jaz6dywsIaJTlF8G1Jrx3PVlUoRHCXZNJe\nxnjKMbGq+/lD00flVHvOWLTfLpSan6IHtE6iG27HOR170FidURHexOFfyZRh251/\nDHlZPIgy2OdOswLSxW34n0HYiaFhHDqnQKu7Y3sF0Hb44QdrKEsy54AUQLM/pbM7\naniXchBwKK0uooZUVp1nsohyKcIDcFsnfOxQih53Mg121DMRVTjWBt2jZ5UcypZY\nEmI8aQtIv51Xl7ZfTrGrord9t1HdMqmmPTWp8oRQnGlboaEckCEYfRlj9WRY/HrA\n4syOfb7D91e+UQbLw1BeDSuYCIcV9Oc2XJLjd6v7QQKBgQDt3YVPNuWPxuYZSyQg\nkA40xgtWe23iGT9mPKJXilNGQ5urMO83zL77wxEKfsKjawp7fn9QuWljCa66p9he\nWpdb4mXWRNJ9Mk8Xh8muyXxow/cyUvi0+SoQymtMjQJwal3WfYS34bKSwV8rKTLg\npBHy26/jCT/FJfO1tFQt66u1LQKBgQDGrAyFkMRCQd2W4oVK8zkcJZwjNaurtyL5\nyMKQCo29JjFDGygPqrbC5BT/i8ITkIXczYLDtreKA9A5QlFg4agLTr1bDTcg7Xeg\nfLBbCL72y/RpblI7zH4VQhJ7rr4b1Lcy9uneKxmgwu7hEgqL0sLEMNFbfaJ+3rHY\nPVM/oZOu5wKBgQC/IORhRkcnRDbX1BzvXVFM7mVl1D/zET50M/xuQuOu7dxDrkpJ\nl+dN/OvQdxKGpRgDKx26C4G25qzTptKg3kIIvt39UcegebA7xAw2ugeRVwVmFm1p\nXVyDqWKWXCe9lHpaQvlFl8EZUu/Zin0rLCqP7h5iW6g2DczKEGAjld6e8QKBgQCb\nxJmsv2yhZnMOslw//6NvZi2djZ8j61sI7VdfCGdJPoCxVMF8RyU0eQ/drP5lyJKs\nJJW6TbBqDcNcoZqck1DmTL46fYoTzxxUQG8lcR4I8rCXWWAwco0Ird1ADCoSOB3L\nX7zN7I0TdsNExJhwOLdsi7oaOc8GGiTmnm5/HXhlUQKBgQDitgKhaetMc7NKaTRP\n0d9ECeMPcdZPHoC6jUcWQFKKNXiSbKwPG51VDbd+58zRlEf+9A2pXObOLDm38iYq\n2vTef1Ullwz47yosenpEWya8SnnxAVpkvT94/d7Q62cRNbMp2hUv7RW82Tgeu7Mk\nvnMw7lAo3Qr8xT+eoQe4jxf17Q==\n-----END PRIVATE KEY-----"
          JWT_PUBLIC_KEY: "-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAuJkxk1KHXlGmpAp8JWjE\npN8zw4n55VMn/0+NK7lUiJBtrZiTAbNWV+mK1svkpTczO57E8qnUALfQcm03Yaao\nMQhXwFyO+ip+3bkmkHFaAspXQPZR8GY5XKvK7v+LIeXj3WFsV0CetlJHpqpM9e/L\nXSNQ/Wa+1xAeI1uCH9y52/6Gkn2hugdLjAFqaFLJ24dslXSsd0TJAxFhoHPgU0zm\nKF0XPBnSzOoZQgDPCIbUPmYcxo2TnjqhjFhxVcOu7Hw0LpwWOivPjZrWqSkHBOhB\ntdvFumUoIgPHYbz06F1GTZwWbIywXoVHHY6KWKL7QGgYNwuy5xZZkYGNPKk7suwR\nmwIDAQAB\n-----END PUBLIC KEY-----"
      - run: |
          cd ./coverage/lcov-report
          npm install -g vercel
          vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}
          vercel deploy --prod --token=${{ secrets.VERCEL_TOKEN }}
